# Author: Daniel Nicolas Gisolfi
# ConvexHull Problem

all: build run

clean:
	@echo "TODO: setup a proper clean function"

build:
	@gcc ./ConvexHull/Divide.c -o Divide

run:
	@./Divide


.PHONY: init test_assignment_1 test_assignment_2